### ISSUE TITLE
Изучить API OK

### ISSUE THREAD

**Issue by AlexanderKiselyov** [AlexanderKiselyov/feed-migrator#1]
1. Найти API OK
2. Изучить особенности
3. Найти способ хранения и передачи информации о группах

**Comment by a-yasevich** [comment]
https://apiok.ru/dev/methods/rest/mediatopic/mediatopic.post
https://apiok.ru/dev/methods/rest/photosV2/photosV2.getUploadUrl
https://apiok.ru/dev/methods/rest/group/group.getStatTopics
