### ISSUE TITLE
Изучить API ВКонтакте

### ISSUE THREAD

**Issue by AlexanderKiselyov** [AlexanderKiselyov/feed-migrator#2]
1. Найти API ВКонтакте
2. Изучить особенности
3. Найти способ хранения и передачи информации о группах

**Comment by Anilochka** [comment]
Формат запросов: https://dev.vk.com/api/api-requests
Ответ: JSON

Методы для запросов для работы с группами (создание, редактирование группы и тд): https://dev.vk.com/method#Groups

Методы для запросов для работы с записями на стене группы/человека (добавление/удаление/изменение записи, получение всех записей со стены, лайков, комментариев, репостов и тд): https://dev.vk.com/method#Wall
- Для бэкапа: https://dev.vk.com/method/wall.get
- Для создания поста: https://dev.vk.com/method/wall.post

 Ограничения на частоту обращений и количественные ограничения на вызов однотипных методов: https://dev.vk.com/api/api-requests#%D0%9E%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B8%20%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B8
