### ISSUE TITLE
Получать название канала вместо того чтобы вставлять короткое имя из ссылки

### ISSUE THREAD

**Issue by a-yasevich** [AlexanderKiselyov/feed-migrator#76]
https://github.com/AlexanderKiselyov/feed-migrator/blob/3d8754a2b44f44e5682ec60ba9ef9a1db0ebeb19/tg-bot/src/main/java/polis/commands/NonCommand.java#L88
https://github.com/AlexanderKiselyov/feed-migrator/blob/3d8754a2b44f44e5682ec60ba9ef9a1db0ebeb19/tg-bot/src/main/java/polis/commands/NonCommand.java#L95

**Comment by AlexanderKiselyov** [comment]
#82
